[package]
name = "sanguinello"
version = "0.0.0"
authors = ["ariel weiss <aweiss@hey.com>"]
license = "BSD-2-Clause"
edition = "2021"

[lib]
name = "sanguinello"
path = "lib/sanguinello.rs"

[dependencies]
bumpalo = { version = "3.16.0", features = ["std", "serde", "boxed", "collections"] }
nom = "7.1.3"
thiserror = "1.0.40"
